### ISSUE TITLE
I'd like to test to know how to use the sample. but an error happens.

### ISSUE THREAD

**Issue by wann2** [jirawatee/ML-Kit-for-Firebase-Android#3]
Hi,
I'd like to test to know how to use the sample. but an error happens.
I am using 
. "build:gradle:3.5.0"
. distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.1-all.zip

When I open the sample in Android studio, the follow error happens.

<img width="1524" alt="ScreenShot_2019-08-31 11 46 22" src="https://user-images.githubusercontent.com/8732515/64058406-94729f80-cbe5-11e9-93ac-943975083bd4.png">

**Comment by jirawatee** [comment]
Did you add your own google-services.json into app folder ?

**Comment by wann2** [comment]
Yes, I added my own google-services.json into app folder.

**Comment by jirawatee** [comment]
Does app package(com.example.mlkit) match with your google-services.json?

**Comment by wann2** [comment]
No. it does not match it. 
Do i have to match it with "com.example.mlkit"?
If so, I wonder if i have to create a new project with the same pakage name in firebase and then re-download google-services.json.

**Comment by jirawatee** [comment]
You have 2 ways
1. Rename "com.example.mlkit" in my source code to package you created in Firebase project.
2. Create a new app and name "com.example.mlkit" as your package name.

*Please be remind, you have to download google-services.json which package name matches each other.

**Comment by wann2** [comment]
Thanks for your kind guide.

**Comment by jirawatee** [comment]
My pleasure.
