### ISSUE TITLE
Using custom tflite model to detect eye region landmarks

### ISSUE THREAD

**Issue by abdou31** [jirawatee/ML-Kit-for-Firebase-Android#4]
Hello Sir,
I have a Tensorflow lite model that can detect eye region, I tried to integrate this model on Android.
The model gives false values compare to the frozen model (tested on python script), I would like to correct the prediction.
I want to use the custommodelActivity.java that you have, but this activity includes the labels text and the model that I used given a regression output, not a classification output.
What can I do?

**Comment by jirawatee** [comment]
Hello @abdou31,
Unfortunately I never tried to use another custom model myself but I guess it is about specifying Input and Output models. Hope this article will help. https://medium.com/firebasethailand/123dfcfdce29.
