### ISSUE TITLE
On Device Text extract?

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [jirawatee/ML-Kit-for-Firebase-Android#5]
hi I am trying to extract text from image using ML kit on device is it free or not how to use ON device free service of google api pls hlep

**Comment by jirawatee** [comment]
Hi Sunil, sorry for my late response.

It is **free with no network required** if you use ML Kit for Firebase features including Barcode Scanning, Face Detection, Image Labeling and Text Recognition with **on-device**.

Please be noted that only **Latin characters** are available in Text Recognition with **on-device**.
In case you would like to extract other kind of characters please consider use **In the Cloud** instead.
